[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install -r requirements.txt --no-cache-dir"
]

[start]
cmd = "python start_server.py"
