name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    - name: Setup Node.js 🔧
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies 📦
      run: npm ci --legacy-peer-deps

    - name: Build 🏗️
      run: npm run build
      env:
        VITE_API_URL: 'https://sp500-predictor-production.up.railway.app'
        VITE_POLYGON_API_KEY: ''

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        branch: gh-pages
        folder: dist
        clean: true
